window.COUNTRIES = [
  // Evropa
  { code: "AL", name: "Albánie" },
  { code: "AD", name: "Andorra" },
  { code: "BE", name: "Belgie" },
  { code: "BY", name: "Bělorusko" },
  { code: "BA", name: "Bosna a Hercegovina" },
  { code: "BG", name: "Bulharsko" },
  { code: "ME", name: "Černá Hora" },
  { code: "CZ", name: "Česko" },
  { code: "DK", name: "Dánsko" },
  { code: "EE", name: "Estonsko" },
  { code: "FI", name: "Finsko" },
  { code: "FR", name: "Francie" },
  { code: "HR", name: "Chorvatsko" },
  { code: "IE", name: "Irsko" },
  { code: "IS", name: "Island" },
  { code: "IT", name: "Itálie" },
  { code: "XK", name: "Kosovo" },
  { code: "CY", name: "Kypr" },
  { code: "LI", name: "Lichtenštejnsko" },
  { code: "LT", name: "Litva" },
  { code: "LV", name: "Lotyšsko" },
  { code: "LU", name: "Lucembursko" },
  { code: "HU", name: "Maďarsko" },
  { code: "MT", name: "Malta" },
  { code: "MD", name: "Moldavsko" },
  { code: "MC", name: "Monako" },
  { code: "DE", name: "Německo" },
  { code: "NL", name: "Nizozemsko" },
  { code: "NO", name: "Norsko" },
  { code: "PL", name: "Polsko" },
  { code: "PT", name: "Portugalsko" },
  { code: "AT", name: "Rakousko" },
  { code: "RO", name: "Rumunsko" },
  { code: "RU", name: "Rusko" },
  { code: "GR", name: "Řecko" },
  { code: "SM", name: "San Marino" },
  { code: "MK", name: "Severní Makedonie" },
  { code: "SK", name: "Slovensko" },
  { code: "SI", name: "Slovinsko" },
  { code: "RS", name: "Srbsko" },
  { code: "ES", name: "Španělsko" },
  { code: "SE", name: "Švédsko" },
  { code: "CH", name: "Švýcarsko" },
  { code: "UA", name: "Ukrajina" },
  { code: "VA", name: "Vatikán" },
  { code: "GB", name: "Velká Británie" },

  // Severní Amerika, Střední Amerika a Karibik
  { code: "AG", name: "Antigua a Barbuda" },
  { code: "BS", name: "Bahamy" },
  { code: "BB", name: "Barbados" },
  { code: "BZ", name: "Belize" },
  { code: "DM", name: "Dominika" },
  { code: "DO", name: "Dominikánská republika" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "JM", name: "Jamajka" },
  { code: "CA", name: "Kanada" },
  { code: "CR", name: "Kostarika" },
  { code: "CU", name: "Kuba" },
  { code: "MX", name: "Mexiko" },
  { code: "NI", name: "Nikaragua" },
  { code: "PA", name: "Panama" },
  { code: "SV", name: "Salvador" },
  { code: "KN", name: "Svatý Kryštof a Nevis" },
  { code: "LC", name: "Svatá Lucie" },
  { code: "VC", name: "Svatý Vincenc a Grenadiny" },
  { code: "TT", name: "Trinidad a Tobago" },
  { code: "US", name: "USA" },

  // Jižní Amerika
  { code: "AR", name: "Argentina" },
  { code: "BO", name: "Bolívie" },
  { code: "BR", name: "Brazílie" },
  { code: "EC", name: "Ekvádor" },
  { code: "GY", name: "Guyana" },
  { code: "CO", name: "Kolumbie" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "SR", name: "Surinam" },
  { code: "UY", name: "Uruguay" },
  { code: "VE", name: "Venezuela" },
  { code: "CL", name: "Chile" },

  // Asie
  { code: "AF", name: "Afghánistán" },
  { code: "AZ", name: "Ázerbájdžán" },
  { code: "BH", name: "Bahrajn" },
  { code: "BD", name: "Bangladéš" },
  { code: "BT", name: "Bhútán" },
  { code: "BN", name: "Brunej" },
  { code: "PH", name: "Filipíny" },
  { code: "GE", name: "Gruzie" },
  { code: "HK", name: "Hongkong" },
  { code: "IN", name: "Indie" },
  { code: "ID", name: "Indonésie" },
  { code: "IQ", name: "Irák" },
  { code: "IR", name: "Írán" },
  { code: "IL", name: "Izrael" },
  { code: "JP", name: "Japonsko" },
  { code: "YE", name: "Jemen" },
  { code: "JO", name: "Jordánsko" },
  { code: "KH", name: "Kambodža" },
  { code: "KZ", name: "Kazachstán" },
  { code: "QA", name: "Katar" },
  { code: "KG", name: "Kyrgyzstán" },
  { code: "CN", name: "Čína" },
  { code: "KW", name: "Kuvajt" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Libanon" },
  { code: "MV", name: "Maledivy" },
  { code: "MY", name: "Malajsie" },
  { code: "MN", name: "Mongolsko" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepál" },
  { code: "OM", name: "Omán" },
  { code: "PK", name: "Pákistán" },
  { code: "PS", name: "Palestina" },
  { code: "SA", name: "Saúdská Arábie" },
  { code: "KP", name: "Severní Korea" },
  { code: "KR", name: "Jižní Korea" },
  { code: "SG", name: "Singapur" },
  { code: "LK", name: "Srí Lanka" },
  { code: "SY", name: "Sýrie" },
  { code: "TJ", name: "Tádžikistán" },
  { code: "TW", name: "Tchaj-wan" },
  { code: "TH", name: "Thajsko" },
  { code: "TR", name: "Turecko" },
  { code: "TM", name: "Turkmenistán" },
  { code: "AE", name: "Spojené arabské emiráty" },
  { code: "UZ", name: "Uzbekistán" },
  { code: "VN", name: "Vietnam" },
  { code: "TL", name: "Východní Timor" },
  { code: "AM", name: "Arménie" },

  // Afrika
  { code: "DZ", name: "Alžírsko" },
  { code: "AO", name: "Angola" },
  { code: "BJ", name: "Benin" },
  { code: "BW", name: "Botswana" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "TD", name: "Čad" },
  { code: "CD", name: "Demokratická republika Kongo" },
  { code: "DJ", name: "Džibutsko" },
  { code: "EG", name: "Egypt" },
  { code: "ER", name: "Eritrea" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Etiopie" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambie" },
  { code: "GH", name: "Ghana" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "ZA", name: "Jihoafrická republika" },
  { code: "SS", name: "Jižní Súdán" },
  { code: "CM", name: "Kamerun" },
  { code: "CV", name: "Kapverdy" },
  { code: "KE", name: "Keňa" },
  { code: "KM", name: "Komory" },
  { code: "CG", name: "Konžská republika" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Libérie" },
  { code: "LY", name: "Libye" },
  { code: "MG", name: "Madagaskar" },
  { code: "MW", name: "Malawi" },
  { code: "ML", name: "Mali" },
  { code: "MA", name: "Maroko" },
  { code: "MU", name: "Mauricius" },
  { code: "MR", name: "Mauritánie" },
  { code: "MZ", name: "Mosambik" },
  { code: "NA", name: "Namibie" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigérie" },
  { code: "CI", name: "Pobřeží slonoviny" },
  { code: "GQ", name: "Rovníková Guinea" },
  { code: "RW", name: "Rwanda" },
  { code: "SN", name: "Senegal" },
  { code: "SC", name: "Seychely" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SO", name: "Somálsko" },
  { code: "CF", name: "Středoafrická republika" },
  { code: "SD", name: "Súdán" },
  { code: "ST", name: "Svatý Tomáš a Princův ostrov" },
  { code: "TZ", name: "Tanzanie" },
  { code: "TG", name: "Togo" },
  { code: "TN", name: "Tunisko" },
  { code: "UG", name: "Uganda" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" },

  // Oceánie
  { code: "AU", name: "Austrálie" },
  { code: "FJ", name: "Fidži" },
  { code: "KI", name: "Kiribati" },
  { code: "MH", name: "Marshallovy ostrovy" },
  { code: "FM", name: "Mikronésie" },
  { code: "NR", name: "Nauru" },
  { code: "NZ", name: "Nový Zéland" },
  { code: "PW", name: "Palau" },
  { code: "PG", name: "Papua-Nová Guinea" },
  { code: "WS", name: "Samoa" },
  { code: "SB", name: "Šalamounovy ostrovy" },
  { code: "TO", name: "Tonga" },
  { code: "TV", name: "Tuvalu" },
  { code: "VU", name: "Vanuatu" },
].sort(function (a, b) {
  return a.name.localeCompare(b.name, "cs");
});
